const ADMIN_PASSWORD='almare2026';const SESSION_KEY='almare_admin_ok';let catalog={products:[],collections:[]};let editingId=null;const $=id=>document.getElementById(id);const toastEl=$('toast');
function showToast(msg,err){toastEl.textContent=msg;toastEl.className='toast show'+(err?' err':'');setTimeout(()=>toastEl.classList.remove('show'),2800)}
function esc(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function checkAuth(){if(sessionStorage.getItem(SESSION_KEY)==='1'){$('loginWrap').style.display='none';$('adminShell').classList.add('open');initAdmin()}}
$('loginBtn').onclick=()=>{if($('pwd').value===ADMIN_PASSWORD){sessionStorage.setItem(SESSION_KEY,'1');checkAuth()}else $('loginErr').style.display='block'};
$('pwd').addEventListener('keydown',e=>{if(e.key==='Enter')$('loginBtn').click()});
$('logoutBtn').onclick=()=>{sessionStorage.removeItem(SESSION_KEY);location.reload()};
document.querySelectorAll('.tab').forEach(tab=>{tab.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(t=>t.classList.remove('active'));document.querySelectorAll('.panel').forEach(p=>p.classList.remove('active'));tab.classList.add('active');$('panel-'+tab.dataset.tab).classList.add('active');if(tab.dataset.tab==='orders')renderOrders();if(tab.dataset.tab==='add'&&!editingId)resetProdForm()})});
async function initAdmin(){try{catalog=await getCatalog()}catch(e){catalog=window.DEFAULT_CATALOG||{products:[],collections:[]}}if(!catalog.products)catalog.products=[];if(!catalog.collections)catalog.collections=[];renderProducts();renderCollections();fillCollectionSelect();$('modeBadge').textContent=(typeof almareIsSupabaseReady==='function'&&almareIsSupabaseReady())?'Supabase':'Locale';$('sbUrl').value=localStorage.getItem('almare_sb_url')||'';$('sbKey').value=localStorage.getItem('almare_sb_key')||'';updateSbStatus();loadGallery()}
function fillCollectionSelect(){const sel=$('prodCollection');const cur=sel.value;sel.innerHTML='<option value="">— Nessuna —</option>'+catalog.collections.map(c=>`<option value="${esc(c.id)}">${esc(c.name)}</option>`).join('');sel.value=cur}
function renderProducts(){const list=$('productsList');if(!catalog.products.length){list.innerHTML='<div class="empty"><p>Nessun prodotto ancora.</p><p>Usa «+ Nuovo prodotto» per iniziare.</p></div>';return}list.innerHTML=catalog.products.map(p=>`<div class="card"><div class="card-row"><img class="card-thumb" src="${esc(p.image)||'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=200&q=60'}" alt="" loading="lazy"><div class="card-body"><h3>${esc(p.name)}</h3><p class="card-meta">${esc(p.category||p.cat||'')}${p.gender?' · '+esc(p.gender):''}${p.age?' · '+esc(p.age):''}</p><p class="card-price">€ ${Number(p.price||0).toFixed(0)}</p><div class="card-actions"><button type="button" class="btn btn-ghost btn-sm" data-edit="${esc(p.id)}">Modifica</button><button type="button" class="btn btn-danger btn-sm" data-del="${esc(p.id)}">Elimina</button></div></div></div></div>`).join('');list.querySelectorAll('[data-edit]').forEach(btn=>{btn.onclick=()=>editProduct(btn.dataset.edit)});list.querySelectorAll('[data-del]').forEach(btn=>{btn.onclick=()=>deleteProduct(btn.dataset.del)})}
function editProduct(id){const p=catalog.products.find(x=>x.id===id);if(!p)return;editingId=id;$('prodId').value=id;$('prodName').value=p.name||'';$('prodPrice').value=p.price||'';$('prodCat').value=p.category||p.cat||'abiti';$('prodGender').value=p.gender||'';$('prodAge').value=p.age||'';$('prodCollection').value=p.collection||p.collectionId||'';$('prodModel').value=p.model||'';$('prodImage').value=p.image||'';$('prodDesc').value=p.description||p.desc||'';if(p.image)$('prodPreview').src=p.image;$('prodFormTitle').textContent='Modifica prodotto';document.querySelector('[data-tab="add"]').click()}
async function deleteProduct(id){if(!confirm('Eliminare questo prodotto?'))return;catalog.products=catalog.products.filter(p=>p.id!==id);await saveCatalog(catalog);renderProducts();showToast('Prodotto eliminato')}
function resetProdForm(){editingId=null;$('prodId').value='';$('prodName').value='';$('prodPrice').value='';$('prodCat').value='abiti';$('prodGender').value='';$('prodAge').value='';$('prodCollection').value='';$('prodModel').value='';$('prodImage').value='';$('prodDesc').value='';$('prodFormTitle').textContent='Nuovo prodotto';$('prodPreview').src="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='140' height='175'%3E%3Crect fill='%23e8dfd0' width='140' height='175'/%3E%3Ctext x='70' y='90' text-anchor='middle' fill='%239a7349' font-size='12'%3EAnteprima%3C/text%3E%3C/svg%3E"}
$('prodImage').addEventListener('input',()=>{const u=$('prodImage').value.trim();if(u)$('prodPreview').src=u});
function handleImageFile(file){if(!file||!file.type.startsWith('image/')){showToast('Seleziona un\'immagine valida',true);return}if(file.size>4*1024*1024){showToast('Immagine troppo grande (max 4 MB)',true);return}const reader=new FileReader();reader.onload=async()=>{const dataUrl=reader.result;$('prodPreview').src=dataUrl;$('prodImage').value=dataUrl;if(typeof uploadProductImage==='function'&&typeof almareIsSupabaseReady==='function'&&almareIsSupabaseReady()){try{const url=await uploadProductImage(file);if(url){$('prodImage').value=url;$('prodPreview').src=url;showToast('Foto caricata su Supabase');loadGallery();return}}catch(e){}}showToast('Foto pronta')};reader.readAsDataURL(file)}
$('fileGallery').addEventListener('change',e=>{if(e.target.files[0])handleImageFile(e.target.files[0]);e.target.value=''});
$('fileCamera').addEventListener('change',e=>{if(e.target.files[0])handleImageFile(e.target.files[0]);e.target.value=''});
async function loadGallery(){const box=$('imgGallery');box.innerHTML='';if(typeof listProductImages==='function'&&typeof almareIsSupabaseReady==='function'&&almareIsSupabaseReady()){try{const imgs=await listProductImages();(imgs||[]).slice(0,24).forEach(url=>{const b=document.createElement('button');b.type='button';b.innerHTML=`<img src="${esc(url)}" alt="">`;b.onclick=()=>{box.querySelectorAll('button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');$('prodImage').value=url;$('prodPreview').src=url};box.appendChild(b)})}catch(e){}}}
$('saveProdBtn').onclick=async()=>{const name=$('prodName').value.trim();const price=Number($('prodPrice').value);if(!name){showToast('Inserisci il nome',true);return}if(!(price>=0)){showToast('Prezzo non valido',true);return}const id=$('prodId').value||('p'+Date.now());const item={id,name,price,category:$('prodCat').value,cat:$('prodCat').value,gender:$('prodGender').value||undefined,age:$('prodAge').value||undefined,collection:$('prodCollection').value||undefined,collectionId:$('prodCollection').value||undefined,model:$('prodModel').value.trim()||undefined,image:$('prodImage').value.trim()||'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=600&q=80',description:$('prodDesc').value.trim()||undefined,desc:$('prodDesc').value.trim()||undefined};const idx=catalog.products.findIndex(p=>p.id===id);if(idx>=0)catalog.products[idx]={...catalog.products[idx],...item};else catalog.products.unshift(item);await saveCatalog(catalog);renderProducts();showToast(editingId?'Prodotto aggiornato':'Prodotto aggiunto');editingId=null;document.querySelector('[data-tab="products"]').click()};
$('cancelProdBtn').onclick=()=>{resetProdForm();document.querySelector('[data-tab="products"]').click()};
function renderCollections(){const list=$('collectionsList');if(!catalog.collections.length){list.innerHTML='<div class="empty"><p>Nessuna collezione.</p></div>';return}list.innerHTML=catalog.collections.map(c=>`<div class="card"><div class="card-row">${c.image?`<img class="card-thumb" src="${esc(c.image)}" alt="">`:''}<div class="card-body"><h3>${esc(c.name)}</h3><p class="card-meta">${esc(c.desc||c.description||'')}</p><div class="card-actions"><button type="button" class="btn btn-ghost btn-sm" data-cedit="${esc(c.id)}">Modifica</button><button type="button" class="btn btn-danger btn-sm" data-cdel="${esc(c.id)}">Elimina</button></div></div></div></div>`).join('');list.querySelectorAll('[data-cedit]').forEach(btn=>{btn.onclick=()=>{const c=catalog.collections.find(x=>x.id===btn.dataset.cedit);if(!c)return;$('collId').value=c.id;$('collName').value=c.name||'';$('collDesc').value=c.desc||c.description||'';$('collImage').value=c.image||'';$('collFormTitle').textContent='Modifica collezione'}});list.querySelectorAll('[data-cdel]').forEach(btn=>{btn.onclick=async()=>{if(!confirm('Eliminare la collezione?'))return;catalog.collections=catalog.collections.filter(c=>c.id!==btn.dataset.cdel);await saveCatalog(catalog);renderCollections();fillCollectionSelect();showToast('Collezione eliminata')}})}
$('saveCollBtn').onclick=async()=>{const name=$('collName').value.trim();if(!name){showToast('Nome obbligatorio',true);return}const id=$('collId').value||('c'+Date.now());const item={id,name,desc:$('collDesc').value.trim(),description:$('collDesc').value.trim(),image:$('collImage').value.trim()};const idx=catalog.collections.findIndex(c=>c.id===id);if(idx>=0)catalog.collections[idx]=item;else catalog.collections.push(item);await saveCatalog(catalog);renderCollections();fillCollectionSelect();$('collId').value='';$('collName').value='';$('collDesc').value='';$('collImage').value='';$('collFormTitle').textContent='Nuova collezione';showToast('Collezione salvata')};
$('cancelCollBtn').onclick=()=>{$('collId').value='';$('collName').value='';$('collDesc').value='';$('collImage').value='';$('collFormTitle').textContent='Nuova collezione'};
function renderOrders(){const list=$('ordersList');let orders=[];try{orders=JSON.parse(localStorage.getItem('almare_orders')||'[]')}catch(e){}if(!orders.length){list.innerHTML='<div class="empty"><p>Nessun ordine ancora.</p><p>Quando un cliente completa il checkout, compare qui.</p></div>';return}list.innerHTML=orders.map(o=>{const items=Array.isArray(o.items)?o.items.map(it=>`${esc(it.name||it.id)} × ${it.qty||1}`).join(', '):(typeof o.items==='string'?esc(o.items):'—');const date=o.created_at||o.date||o.id||'';return `<div class="card order-card"><div class="order-head"><div><div class="order-id">${esc(o.customer_name||o.name||'Cliente')}</div><div class="order-date">${esc(String(date).slice(0,19))}</div></div><div class="order-total">€ ${Number(o.total||0).toFixed(0)}</div></div><p class="card-meta">${esc(o.email||'')}${o.phone?' · '+esc(o.phone):''}</p><p class="card-meta">${esc(o.address||'')}${o.city?' · '+esc(o.city):''}</p><div class="order-items">${items}</div>${o.notes?`<p class="card-meta">Note: ${esc(o.notes)}</p>`:''}</div>`}).join('')}
function updateSbStatus(){const ok=typeof almareIsSupabaseReady==='function'&&almareIsSupabaseReady();$('sbStatus').textContent=ok?'Collegato a Supabase':'Modalità locale (localStorage)';$('modeBadge').textContent=ok?'Supabase':'Locale'}
$('saveSbBtn').onclick=()=>{localStorage.setItem('almare_sb_url',$('sbUrl').value.trim());localStorage.setItem('almare_sb_key',$('sbKey').value.trim());if(window.ALMARE_CONFIG){window.ALMARE_CONFIG.SUPABASE_URL=$('sbUrl').value.trim();window.ALMARE_CONFIG.SUPABASE_ANON_KEY=$('sbKey').value.trim()}updateSbStatus();showToast('Configurazione salvata')};
$('seedBtn').onclick=async()=>{if(typeof seedSupabaseIfEmpty==='function'){await seedSupabaseIfEmpty();catalog=await getCatalog();renderProducts();renderCollections();showToast('Sincronizzazione completata')}else showToast('Funzione non disponibile',true)};
checkAuth();
